Azure Pipelines for Releases (#34)
* add ReleaseVersion parameter

* start adding publish steps

* fix pool references:

* just use linuxpool

* make publish stage name consistent

* some debugging stuff, and pick the right artifact

* set version to 0.0.7

* set version to 0.1.0

* commit to release staging branch

* add the files to git

* try persistCredentials

* Wait for confirmation, then push tag

* Automate version selection

* remove unnecessary prepare step

* lets just commit to the staging branch for now

* Wait for validation before staging release

* Use Microsoft-internal toolchain for release builds

* Use msdata toolchain feed

* replace rust-toolchain before installing msrustup

* remove rust-analyzer component from internal build toolchain

* reorganize tasks a bit

* there is no internal Windows GNU toolchain

* restore toolchain file rename

* authenticate to Azure feed any time we swap to it

* force push to staging branch

* add aarch64-unknown-linux-gnu output

* update Go build

* update email address used in release pipeline

* don't run tests when cross compiling

* build ON aarch64 instead of cross compiling

* switch to ARM pools for ARM builds

* disable python on aarch64 linux

* fix bootstrap.ps1

* switch to detecting python in the bootstrap sceript

* install just if necessary

* remove requirement for vendored openssl

* remove cross-linker

* install c compiler when needed

* use tdnf to install packages on Azure Linux

* only check for cc on linux

* install powershell if necessary

* try manual install

* fix tyop

* just assume Linux means Ubuntu for now

* remove check for cc

* back to cross-compilation

* fix tyop

* set up cross-compiling before Go

* try on the arm agent again

* disable python on arm builds

* disable arm and cargo cache for now

* fix version detection

* update-version script

* display name for detecting version step

* update changelog

* remove commented-out cache task

diff --git a/script/pipelines/pipeline-template.yml b/script/pipelines/pipeline-template.yml
--- a/script/pipelines/pipeline-template.yml
+++ b/script/pipelines/pipeline-template.yml
@@ -2,7 +2,12 @@ parameters:
   - name: IsReleaseBuild
     type: boolean
     default: false
+  - name: UseMicrosoftToolChain
+    type: boolean
+    default: false
   - name: LinuxPool
+    type: object
+  - name: LinuxARM64Pool
     type: object
   - name: MacPool
     type: object
@@ -25,6 +30,8 @@ stages:
         pool: ${{ parameters.LinuxPool }}
         steps:
           - template: prep-agent.yml
+            parameters:
+              IsReleaseBuild: ${{ parameters.IsReleaseBuild }}
           - pwsh: script/check-headers.ps1
             displayName: "Check headers"
           - script: just check
@@ -47,6 +54,8 @@ stages:
           - template: prep-agent.yml
             parameters:
               HostIsWindows: true
+              IsReleaseBuild: ${{ parameters.IsReleaseBuild }}
+              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}
 
           - template: emulator-setup.yml
 
@@ -68,9 +77,10 @@ stages:
               RustTarget: x86_64-pc-windows-msvc
               HostIsWindows: true
               PublishArtifacts: ${{ parameters.IsReleaseBuild }}
+              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}
 
               # Go doesn't support MSVC-built libraries, we'll test it in the x86_64-pc-windows-gnu build
-              RunGoTests: false 
+              RunGoTests: false
               VendorForGo: false
 
       - job: x86_64_pc_windows_gnu
@@ -82,6 +92,7 @@ stages:
               RustTarget: x86_64-pc-windows-gnu
               HostIsWindows: true
               PublishArtifacts: ${{ parameters.IsReleaseBuild }}
+              UseMicrosoftToolchain: false # There is no internal x86_64-pc-windows-gnu toolchain
 
       - job: x86_64_linux_gnu
         displayName: "Linux x86_64"
@@ -91,6 +102,7 @@ stages:
             parameters:
               RustTarget: x86_64-unknown-linux-gnu
               PublishArtifacts: ${{ parameters.IsReleaseBuild }}
+              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}
 
       - job: x86_64_apple_darwin
         displayName: "macOS x86_64"
@@ -100,6 +112,7 @@ stages:
             parameters:
               RustTarget: x86_64-apple-darwin
               PublishArtifacts: ${{ parameters.IsReleaseBuild }}
+              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}
 
       - job: aarch64_apple_darwin
         displayName: "macOS aarch64"
@@ -109,10 +122,11 @@ stages:
             parameters:
               RustTarget: aarch64-apple-darwin
               PublishArtifacts: ${{ parameters.IsReleaseBuild }}
+              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}
 
               # The job runs on an x86_64 machine, so we can't run tests.
-              RunGoTests: false 
-              RunRustTests: false 
+              RunGoTests: false
+              RunRustTests: false
 
   - ${{ if eq(parameters.IsReleaseBuild, true) }}:
       - stage: Package
@@ -150,3 +164,63 @@ stages:
               - publish: output
                 displayName: "Publish packages"
                 artifact: "packages"
+
+      - stage: Stage
+        dependsOn:
+          - Package
+          - Validate
+        jobs:
+          - job: publish_go
+            displayName: "Publish Go Wrapper"
+            pool: ${{ parameters.LinuxPool }}
+            steps:
+              - checkout: self
+                fetchTags: true
+                persistCredentials: true
+              - download: current
+                artifact: packages
+                patterns: "**"
+              - bash: |
+                  version=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "cosmoscx") | .version')
+                  tag_name="go/azcosmoscx/v$version"
+                  branch_name="azp-release-staging/v$version"
+                  echo "##vso[task.setvariable variable=ReleaseVersion]$version"
+                  echo "##vso[task.setvariable variable=ReleaseTag]$tag_name"
+                  echo "##vso[task.setvariable variable=ReleaseBranch]$branch_name"
+                displayName: "Detecting package version"
+              - bash: |
+                  echo "Preparing Go wrapper release tag '$(ReleaseTag)'"
+                  if git rev-parse -q --verify "refs/tags/$(ReleaseTag)" >/dev/null; then
+                    echo "Error: Git tag '$(ReleaseTag)' already exists. Aborting release."
+                    exit 1
+                  fi
+
+                  git checkout -b "$(ReleaseBranch)"
+
+                  src_dir="$(Pipeline.Workspace)/packages/vendored"
+                  dest_dir="./go/azcosmoscx/libcosmoscx-vendor"
+
+                  echo "Creating destination directory '$dest_dir'"
+                  mkdir -p "$dest_dir"
+
+                  # Ensure there is at least one subdirectory to copy
+                  if ! find "$src_dir" -maxdepth 1 -mindepth 1 -type d -print -quit >/dev/null 2>&1; then
+                    echo "No subdirectories found in '$src_dir' to copy."
+                    exit 1
+                  fi
+
+                  echo "Copying subdirectories from '$src_dir' into '$dest_dir' (subdirs become direct children)"
+                  # rsync copies the contents of src_dir into dest_dir, making each top-level subdirectory a direct child
+                  rsync -a --chmod=ugo=rwX "$src_dir"/ "$dest_dir"/
+
+                  echo "Copy complete."
+                displayName: "Place vendored binaries"
+              - bash: |
+                  git add go/azcosmoscx/libcosmoscx-vendor
+                  git config --global user.name "Azure CosmosDB SDK Automation"
+                  git config --global user.email "azurecosmossdk@microsoft.com"
+                  git commit -m"Updating vendored binaries to $(ReleaseVersion)"
+
+                  # It's OK to force push here. Any time we're running this pipeline, we want to replace any bits in the release branch with the new ones.
+                  git push --force origin $(ReleaseBranch)
+                displayName: Commit to release staging branch
