time out the wait for the emulator to start

diff --git a/script/start-emulator b/script/start-emulator
--- a/script/start-emulator
+++ b/script/start-emulator
@@ -3,9 +3,22 @@ script_dir=$(dirname "$(readlink -f "$0")")
 cd "$script_dir/.."
 repo_root="$PWD"
 
+set -euo pipefail
+
+if [ ! -d "$repo_root/.local/cosmos-emulator-data" ]; then
+    echo "Creating local cosmos emulator data directory..."
+    mkdir -p "$repo_root/.local/cosmos-emulator-data"
+fi
+
 docker compose up -d
 
+count=0
 while ! curl --insecure --silent --fail --output /dev/null https://localhost:8081/_explorer/index.html; do
+    if [ $count -gt 10 ]; then
+        echo "Emulator failed to start after 10 attempts."
+        exit 1
+    fi
+    count=$((count + 1))
     echo "Waiting for emulator to start..."
     sleep 5
 done
